name: cakramedic
description: Aplikasi booking dan management

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  horizontal_calendar_widget: ^1.0.1
  http: ^0.12.0+2
  flushbar:
  modal_progress_hud: ^0.1.3
  bubble_tab_indicator: ^0.1.4
  datetime_picker_formfield: ^1.0.0
  carousel_pro: ^1.0.0
  qr_flutter: ^3.2.0
  font_awesome_flutter: ^8.0.1
  package_info: ^0.4.0+9
  url_launcher: ^5.1.4
  image_picker: ^0.6.1+8
  sliding_up_panel: ^0.3.6
  flutter_secure_storage: ^3.3.1+1
  intl: ^0.16.1
  connectivity:
  splashscreen:
  random_string: ^2.0.1
  intro_slider: ^2.2.8
  toast: ^0.1.5
  double_back_to_close_app: ^0.1.2
  local_auth: ^0.6.1+3
  provider: ^3.1.0
  shared_preferences: ^0.5.3+4
  theme_provider: ^0.3.2
  bezier_chart: ^1.0.16
  fl_chart: ^0.8.7
  month_picker_dialog: ^0.3.1
  money2: ^1.3.0
  date_range_picker: ^1.0.6
  tutorial_coach_mark: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/siang.png
    - assets/malam.png
    - assets/slider01.png
    - assets/dokter.png
    - assets/pasien.png
    - assets/28533.jpg
    - assets/2547803.jpg
    - assets/kartu_nama.png
    - assets/tutorial/tips1.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: LinoWrite
      fonts:
        - asset: assets/fonts/linowrite/linowrite.ttf

    - family: SUNDAY
      fonts:
        - asset: assets/fonts/SUNDAY/SUNDAY.ttf

    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Bold.ttf

    - family: OpenSans-Semibold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Semibold.ttf

    - family: OpenSans-ExtraBold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-ExtraBold.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
